// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzLV9_eJ6wiSBWWi8jUlqBEixBoI1qVs',
    appId: '1:44510558997:web:a7adde769f770ccfb3471c',
    messagingSenderId: '44510558997',
    projectId: 'volunity-f6738',
    authDomain: 'volunity-f6738.firebaseapp.com',
    storageBucket: 'volunity-f6738.appspot.com',
    measurementId: 'G-X0LTV8GNPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgFphxSnQedM0CQHxR4K9YGhpJCKzmCgg',
    appId: '1:44510558997:android:860af5ff8b1ff958b3471c',
    messagingSenderId: '44510558997',
    projectId: 'volunity-f6738',
    storageBucket: 'volunity-f6738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlfi9qCVAKcXfHtq4AfoMrM4XO9JfrjU',
    appId: '1:44510558997:ios:7e3c57a558db8416b3471c',
    messagingSenderId: '44510558997',
    projectId: 'volunity-f6738',
    storageBucket: 'volunity-f6738.appspot.com',
    iosClientId: '44510558997-5f4tmsk24v38gacref23go7i6ut15nnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlfi9qCVAKcXfHtq4AfoMrM4XO9JfrjU',
    appId: '1:44510558997:ios:7e3c57a558db8416b3471c',
    messagingSenderId: '44510558997',
    projectId: 'volunity-f6738',
    storageBucket: 'volunity-f6738.appspot.com',
    iosClientId: '44510558997-5f4tmsk24v38gacref23go7i6ut15nnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunity',
  );
}
